# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import review_pb2 as review__pb2


class CodeReviewServiceStub(object):
    """The service definition — what RPCs are available
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BatchReview = channel.unary_stream(
                '/review.CodeReviewService/BatchReview',
                request_serializer=review__pb2.BatchReviewRequest.SerializeToString,
                response_deserializer=review__pb2.ReviewResponse.FromString,
                )


class CodeReviewServiceServicer(object):
    """The service definition — what RPCs are available
    """

    def BatchReview(self, request, context):
        """Takes multiple files, returns multiple reviews (server-side streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CodeReviewServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BatchReview': grpc.unary_stream_rpc_method_handler(
                    servicer.BatchReview,
                    request_deserializer=review__pb2.BatchReviewRequest.FromString,
                    response_serializer=review__pb2.ReviewResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'review.CodeReviewService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CodeReviewService(object):
    """The service definition — what RPCs are available
    """

    @staticmethod
    def BatchReview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/review.CodeReviewService/BatchReview',
            review__pb2.BatchReviewRequest.SerializeToString,
            review__pb2.ReviewResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
