# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: review.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0creview.proto\x12\x06review\"<\n\x08\x43odeFile\x12\x10\n\x08language\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t\"F\n\x12\x42\x61tchReviewRequest\x12\x1f\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x10.review.CodeFile\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"t\n\x0eReviewResponse\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x0f\n\x07summary\x18\x03 \x01(\t\x12\r\n\x05score\x18\x04 \x01(\x05\x12\x0f\n\x07success\x18\x05 \x01(\x08\x12\r\n\x05\x65rror\x18\x06 \x01(\t2X\n\x11\x43odeReviewService\x12\x43\n\x0b\x42\x61tchReview\x12\x1a.review.BatchReviewRequest\x1a\x16.review.ReviewResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'review_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CODEFILE']._serialized_start=24
  _globals['_CODEFILE']._serialized_end=84
  _globals['_BATCHREVIEWREQUEST']._serialized_start=86
  _globals['_BATCHREVIEWREQUEST']._serialized_end=156
  _globals['_REVIEWRESPONSE']._serialized_start=158
  _globals['_REVIEWRESPONSE']._serialized_end=274
  _globals['_CODEREVIEWSERVICE']._serialized_start=276
  _globals['_CODEREVIEWSERVICE']._serialized_end=364
# @@protoc_insertion_point(module_scope)
